sudo: false
language: ruby
cache: bundler
rvm:
- 2.5.1
install:
- bundle install
script: bundle exec rake site:deploy --quiet
env:
  global: 
branches:
  only:
  - master
irisliucy/irisliucy:
  github:
    io:
      secure: UQ1aPq8QBphMtE2LZDoxw8DU95NAxqcI/BId2k5xJqNlh3N21kWCh1KB1z/eXNEWIdscs3V23elhEFIwT7TXjcbDwZa1D/FileEKfhNwLxI2nNKwM7OKF6Z7fnurs25tRYYii3qrSV6YBlL3JQEx9NO9m2ULg3WoxJw4Yrj8JDz45Pnti81T1LB+5bqb7VZRAP5Z57bng08ZSZDJZJFgXaeO0FLXeMdcjHi1Ftz36XnidK+EF6lXJYZ5XzorUJwu2qpMzainBLDXoSUF6WUY/fOEwX8v3GXMrbq1FG+2pHB1XVXe8H7Fbm8shwGciG9u3WgxCCYEhT6EvBvg+jIjPPAp/TZwOcBocuaXZdz++LeOZCxRIdnwBlYSSoM7YIeUkQmRtn+QwV5iARu77Dcw4+asBe/KkL5IwjlgkjL2oplqiYPsZzTO6Ql+NEhvA1jjbRp25Ln0opXFW6bTt54Fw6UjMIHCsHEY1FLVBVl7GIumxKD/enQgSUaiOLcGvK1O5qq7/Asgo2l3+iw0vfi2bcW9QHBCzGFIPNlQyJzMOOtbUJwwScV8yzDWRFj+TCRvJsfymrqMOe75YA0fjC5yU21iRJIQFJ5u47VpGGcZmOyK2uibLgwK2TKWRbsAbqSS3GjV/Ke2WCEChFt/XyXfYl4E+837YF4q5B753u8iZIg=
